config_1:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "crack"]
    force_directory: True

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 128
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 128
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50

config_2:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "crack"]
    force_directory: False

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 256
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 256
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50

config_3:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "crack"]
    force_directory: False

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 512
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 512
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50

config_4:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "transverse", "longitudinal", "diagonal", "other" ]
    force_directory: True

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 256
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 256
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50

config_5:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "block", "crocodile", "meandering", "crescent", "other"]
    force_directory: True

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 256
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 256
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50

config_6:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "block", "crocodile", "meandering", "transverse", "longitudinal", "diagonal", "crescent"]
    force_directory: True

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 256
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 256
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50