config_7:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "crack"]
    force_directory: True

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 1024
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 1024
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50

config_8:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "transverse", "other"]
    force_directory: True

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 1024
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 1024
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50

config_9:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "transverse", "longitudinal", "other"]
    force_directory: True

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 1024
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 1024
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50

config_10:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "transverse", "longitudinal", "diagonal", "other"]
    force_directory: True

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 1024
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 1024
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50

config_11:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "transverse", "longitudinal", "diagonal", "meandering", "other"]
    force_directory: True

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 1024
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 1024
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50

config_12:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "transverse", "longitudinal", "diagonal", "meandering", "block", "other"]
    force_directory: True

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 1024
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 1024
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50

config_13:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "transverse", "longitudinal", "diagonal", "meandering", "block", "crocodile", "other"]
    force_directory: True

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 1024
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 1024
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50

config_14:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "transverse", "longitudinal", "diagonal", "meandering", "block", "crocodile", "crescent"]
    force_directory: True

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 1024
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 1024
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "DeepLabV3Plus"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"

  trainer:
    epochs: 50