config_2:
  splitter:
    task: "segmentation"
    test_val_ratio: 0.2
    classes_list: [ "background", "transverse", "longitudinal", "other" ]
    force_directory: True

  datasets:
    train:
      iterator:
        set_name: "train"
        patch_size: 128
        augment: True
      loader:
        batch_size: 4
        shuffle: True
        num_workers: 4
        report: True
    val:
      iterator:
        set_name: "val"
        patch_size: 128
        augment: False
      loader:
        batch_size: 4
        shuffle: False
        num_workers: 4
        report: True

  model:
    model_name: "Unet"
    encoder_name: "resnet34"
    encoder_weights: "imagenet"

  trainer:
    epochs: 2